In [1]:
# Working with Graphd: we have a module named scipy.sparse.csgraph

# Adjacency Matrix: nxn matrix where n is the number of element in the graph.

# Connected Component:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix
var = np.array([[0,1,2],[1,0,0],[2,0,0]])
var1 = csr_matrix(var)
print(connected_components(var1))

(1, array([0, 0, 0]))


In [2]:
#DIJKSTRA'S METHOD: for finding the shortest path in a graph from one element to another
# it take 2 arg: return_predecessors, indices, limit
# here we will find shortes path from element 1 ro 2:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix
var = np.array([[0,1,2],[1,0,0],[2,0,0]])
var1 = csr_matrix(var)
print(dijkstra(var1,return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


In [3]:
# Floyd Warshall() method: it is for finding the shortest
# path between all the pairs of elements.

import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix
var = np.array([[0,1,2],[1,0,0],[2,0,0]])
var1 = csr_matrix(var)
print(floyd_warshall(var1,return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


In [4]:
# Bellman_ford() method: it is for finding the shortest path
# between all the pairs of elements but this method can handle negative weight as well.

import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix
var = np.array([[0,1,2],[1,0,0],[2,0,0]])
var1 = csr_matrix(var)
print(bellman_ford(var1,return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


In [6]:
# Depth first order: it returns a depth first traversal from node: it has 2 argu: the graph, starting element

import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix
var = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
var1 = csr_matrix(var)
print(depth_first_order(var1, 1))

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


In [7]:
# Breadth first order: it returns a  firsbreadtht traversal from node: it has 2 argu: the graph, starting element

import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix
var = np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
var1 = csr_matrix(var)
print(breadth_first_order(var1, 1))

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))
