In [1]:
#printing minimuum element of the array
import numpy as np

var = np.array([1,2,6,7,37,97,314])

print("minimum :", np.min(var))

minimum : 1


In [2]:
#printing maximum element of the array
import numpy as np

var = np.array([1,2,6,7,37,97,314])

print("maximum :", np.max(var))

minimum : 314


In [5]:
#printing minimum element of the array as well as the position of that minimum element
import numpy as np

var = np.array([2,1,6,-123,7,37,97,314])

print("minimum :", np.min(var), np.argmin(var))

minimum : -123 3


In [6]:
#printing maximum element of the array as well as the position of that maximum element
import numpy as np

var = np.array([2,1,6,-123,7,37,97,314])

print("maximum :", np.max(var), np.argmax(var))

maximum : 314 7


In [9]:
#printing maximum and minimum element of the array in 2-dimensional array
#here we have to used axis as a parameter along with min or max function
#axis=1 [for row operation means it will be used to check minimum and maximum elements of the array in row wise manner]
#axis=0 [for column operation means it will be used to check minimum and maximum elements of the array in column wise manner]

var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis=0)) #printing minimum in column wise manner

print(np.min(var1,axis=1))  #printing minimum in row wise manner

[2 1 3]
[1 5]


In [10]:
#printing maximum and minimum element of the array in 2-dimensional array
#here we have to used axis as a parameter along with min or max function
#axis=1 [for row operation means it will be used to check minimum and maximum elements of the array in row wise manner]
#axis=0 [for column operation means it will be used to check minimum and maximum elements of the array in column wise manner]

var1 = np.array([[2,1,3],[9,5,6]])

print(np.max(var1,axis=0)) #printing maximum in column wise manner

[9 5 6]


In [11]:
#printing maximum and minimum element of the array in 2-dimensional array
#here we have to used axis as a parameter along with min or max function
#axis=1 [for row operation means it will be used to check minimum and maximum elements of the array in row wise manner]
#axis=0 [for column operation means it will be used to check minimum and maximum elements of the array in column wise manner]

var1 = np.array([[2,1,3],[9,5,6]])

print(np.max(var1,axis=1)) #printing maximum in row wise manner

[3 9]


In [12]:
#prinitng sqrt of elements of the array

import numpy as np

var = np.array([1,4,9,16,25])

print(np.sqrt(var))

[1. 2. 3. 4. 5.]


In [13]:
#printning sine values of the each elements of the array

import numpy as np

var = np.array([1,4,9,16,25])

print(np.sin(var))

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [14]:
#printning cos values of the each elements of the array

import numpy as np

var = np.array([1,4,9,16,25])

print(np.cos(var))

[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


In [15]:
#printing cummulative(cum sum) sum of the elements of the array

import numpy as np

var = np.array([1,4,9,16,25])

print(np.cumsum(var))

[ 1  5 14 30 55]
