In [1]:
#arthemitc operation
#addition of a constant term with each element of array in 1-dimensional array
import numpy as np

var = np.array([1,2,3,4,5])

varadd = var + 3

print(varadd)

[4 5 6 7 8]


In [2]:
#addition of two 1-dimensional arrays

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varadd = var1 + var2

print(varadd)

[ 7  9 11 13 15]


In [3]:
#arthemitc operation
#subtraction of a constant term with each element of array in 1-dimensional array
import numpy as np

var = np.array([1,2,3,4,5])

varsub = var - 3

print(varsub)

[-2 -1  0  1  2]


In [4]:
#subtraction of two 1-dimensional arrays

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varsub = var1 - var2

print(varsub)

[-5 -5 -5 -5 -5]


In [6]:
#arthemitc operation
#multiplication of a constant term with each element of array in 1-dimensional array
import numpy as np

varmul = np.array([1,2,3,4,5])

varsub = var * 3

print(varmul)

[1 2 3 4 5]


In [7]:
#multiplication of two 1-dimensional arrays

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varmul = var1 * var2

print(varmul)

[ 6 14 24 36 50]


In [8]:
#arthemitc operation
#division of a constant term with each element of array in 1-dimensional array
import numpy as np

varmul = np.array([1,2,3,4,5])

vardiv = var % 3

print(vardiv)

[1 2 0 1 2]


In [9]:
#division of two 1-dimensional arrays

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

vardiv = var1 % var2

print(vardiv)

[1 2 3 4 5]


In [12]:
#addition in 2-dimensional array

var21 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
var22 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(var21)
print()

print(var22)
print()

varadd2 = var21 + var22

print(varadd2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 2  4  6  8 10]
 [12 14 16 18 20]]
