In [1]:
#DATA TYPE
#integer

import numpy as np

var = np.array([1,2,3,4,5])
print("Data type : ", var.dtype)

Data type :  int32


In [2]:
#float

import numpy as np

var = np.array([1.0,2.0,3.0,4.0,5.0])
print("Data type : ", var.dtype)

Data type :  float64


In [3]:
#string

import numpy as np

var = np.array(["A","B","C","D","E"])
print("Data type : ", var.dtype)

Data type :  <U1


In [4]:
import numpy as np

var = np.array(["A","B","C","D","E",1,2,3,4,5])
print("Data type : ", var.dtype)

Data type :  <U11


In [6]:
 #conversion of int32 to int8 data type
x = np.array([1,2,3 ,4,5],dtype = np.int8)

print("Data type : ", x.dtype)
print(x)

Data type :  int8
[1 2 3 4 5]


In [7]:
#conversion of int data type to float data type
x1 = np.array([1,2,3 ,4,5],dtype = "f")

print("Data type : ", x1.dtype)
print(x1)

Data type :  float32
[1. 2. 3. 4. 5.]


In [9]:
#conversion of int data type to float data type through function
x2 = np.array([1,2,3 ,4,5])

new = np.float32(x2)

print("Data Type :", x2.dtype)
print("Data type : ", new.dtype)

print(x2)
print(new)

Data Type : int32
Data type :  float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [11]:
#conversion of float data type to int data type through function
x2 = np.array([1,2,3 ,4,5])

new = np.float32(x2)

new_one = np.int_(new)

print("Data Type :", x2.dtype)
print("Data type : ", new.dtype)
print("Data type : ", new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type : int32
Data type :  float32
Data type :  int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [12]:
#conversion of data types directly by using astype function

x3 = np.array([1,2,3,4,5])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
