In [6]:
#indexing

import numpy as np

var = np.array([9,8,7,6])
   #            0,1,2,3     indexing starting from zero
   #            -4,-3,-2,-1  indexing starting from -4 to -1

print(var[1])
print(var[-3])  


8
8


In [7]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [8]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [10]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2[0,0,1])

[[[1 2]
  [6 7]]]
3

2


In [9]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()

print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


In [12]:
#SLICING

import numpy as np

var = np.array([1,2,3,4,5,6,7])
     #          0,1,2,3,4,5,6
print(var)
print()

print("2 to 5 : ",var[1:5])

[1 2 3 4 5 6 7]

2 to 5 :  [2 3 4 5]


In [13]:
#SLICING

import numpy as np

var = np.array([1,2,3,4,5,6,7])
     #          0,1,2,3,4,5,6
print(var)
print()

print("2 to End : ",var[1:])

[1 2 3 4 5 6 7]

2 to End :  [2 3 4 5 6 7]


In [14]:
#SLICING

import numpy as np

var = np.array([1,2,3,4,5,6,7])
     #          0,1,2,3,4,5,6
print(var)
print()

print("2 to 6 : ",var[1:6:2])

[1 2 3 4 5 6 7]

2 to 6 :  [2 4 6]


In [15]:
#SLICING

import numpy as np

var = np.array([1,2,3,4,5,6,7])
     #          0,1,2,3,4,5,6
print(var)
print()

print("start to 5 : ",var[:5])

[1 2 3 4 5 6 7]

start to 5 :  [1 2 3 4 5]


In [19]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()

print("8 to 5 :",var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [8 7 6 5]
