In [1]:
#INSERT

import numpy as np

var = np.array([1,2,3,4])

print(var)

v = np.insert(var,2,40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4]


In [3]:
#INSERT

import numpy as np

var = np.array([1,2,3,4])

print(var)

v = np.insert(var,(2,4),40)

print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [4]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1,2,6,axis=0)

print(v1)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [5]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1,2,6,axis=1)

print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [6]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1,2,[22,23,24],axis=0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


In [9]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1,2,[22,23],axis=1)

print(v1)

[[ 1  2 22  3]
 [ 1  2 23  3]]


In [12]:
#APPEND FUNCTION

var = np.array([1,2,3,4])

print(var)

v = np.append(var,6.5)

print(v)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [13]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.append(var1,[[45,44,34]],axis=0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44 34]]


In [15]:
#DELETE FUNCTION

var = np.array([1,2,3,4])

print(var)

v = np.delete(var,2)

[1 2 3 4]
