In [2]:
#JOIN ARRAY : joining means putting contents of two or more arrays in a single array
#JOIN ARRAY

import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1)) #concatenate function is used to join arrays

print(ar)

[1 2 3 4 9 8 7 6]


In [3]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis=1)

print(vr)
print()
print(vr1)
print()

print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [4]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis=0)

print(vr)
print()
print(vr1)
print()

print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [5]:
#joinig using stack function
var_1 = np.array([1,2,3,4])
var_2= np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis=1)

print(a_new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [6]:
var_1 = np.array([1,2,3,4])
var_2= np.array([9,8,7,6])

a_new = np.hstack((var_1,var_2))     #if we put h then it will join the row-wise

print(a_new)

[1 2 3 4 9 8 7 6]


In [8]:
var_1 = np.array([1,2,3,4])
var_2= np.array([9,8,7,6])

a_new = np.vstack((var_1,var_2))     #if we put v then it will join the column-wise

print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [9]:
var_1 = np.array([1,2,3,4])
var_2= np.array([9,8,7,6])

a_new = np.dstack((var_1,var_2))     #if we put d then it will join the height-wise

print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [10]:
#SPLIT ARRAY

import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print()

print(ar)


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print()

print(ar)
print(type(ar))


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [12]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print()
print(ar2)

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
