In [1]:
#MATRIX

import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [2]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [7]:
#matrix addition
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var+var2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


In [6]:
#matrix subtraction
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var-var2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[0 0 0]
 [0 0 0]]


In [9]:
#matrix multiplication

import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var*var2)
print()

print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [10]:
#ARRAY multiplication

var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [11]:
#TRANSPOSE MATRIX

import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)

print(np.transpose(var))

[[1 2 3]
 [1 2 3]]
[[1 1]
 [2 2]
 [3 3]]


In [13]:
#TRANSPOSE MATRIX

import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)

print(var.T)

[[1 2 3]
 [1 2 3]]
[[1 1]
 [2 2]
 [3 3]]


In [17]:
#SWAPAXES
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)
 
print(np.swapaxes(var,0,1))


[[1 2 3]
 [1 2 3]]
[[1 1]
 [2 2]
 [3 3]]


In [18]:
#SWAPAXES
import numpy as np

var2 = np.matrix([[1,2],[1,2]])

print(var2)
print()
 
print(np.swapaxes(var2,0,1))


[[1 2]
 [1 2]]

[[1 1]
 [2 2]]


In [20]:
#INVERSE MATRIX

var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()

print(np.linalg.inv(var2))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
#POWER MATRIX

var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()

print(np.linalg.matrix_power(var2,2))
print()


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]



In [23]:
#POWER MATRIX

var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()

print(np.linalg.matrix_power(var2,0))
print()


[[1 2]
 [3 4]]

[[1 0]
 [0 1]]



In [24]:
#POWER MATRIX

var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()

print(np.linalg.matrix_power(var2,-2))
print()


[[1 2]
 [3 4]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [25]:
#DETERMINATE MATRIX

#POWER MATRIX

var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()

print(np.linalg.det(var2))
print()


[[1 2]
 [3 4]]

-2.0000000000000004

