In [2]:
#SEARCH

import numpy as np

var = np.array([1,2,3,4,5,2,7,2,9])
#index          0,1,2,3,4,5,6,7,8

x = np.where(var == 2)

print(x)

(array([1, 5, 7], dtype=int64),)


In [5]:
#SEARCH

import numpy as np

var = np.array([1,2,3,4,5,2,7,2,9])
#index          0,1,2,3,4,5,6,7,8

x = np.where((var%2) == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [11]:
#SEARCH SORTED ARRAY : which performs a binary search in the array, and returns the indices where the specified values would be inserted to maintain the search order

import numpy as np

var1 = np.array([1,2,3,4,2,7,2,9])
#index          0,1,2,3,4,5,6,7

x1 = np.searchsorted(var1, 5)

print(x1)

7


In [12]:
var1 = np.array([1,2,3,4,9,10])

x1 = np.searchsorted(var1, [5,6,7],side="right")

print(x1)

[4 4 4]


In [13]:
#SORT ARRAY: ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical,ascending or descending
#SORT

var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))


[ 1  2  3  4  5  6  7 12 22 52]


In [14]:
var_1 = np.array(["z","p","a","m","e"])

print(np.sort(var_1))

['a' 'e' 'm' 'p' 'z']


In [15]:
var_1 = np.array([[4,2,3],[1,12,5],[22,52,6]])  #sort function in 2-dimensional array

print(np.sort(var_1))


[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [21]:
#FILTER ARRAY:- Getting some elements out of an existing array and creating a new array out of them
#FILTER ARRAY

var_3 = np.array(["z","p","a","m"])

f = [True,False,False, True]

new_a = var_3[f]

print(new_a)
print(type(new_a))

['z' 'm']
<class 'numpy.ndarray'>


In [23]:
#SHUFFLE ARRAY

import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)


[3 2 4 1 5]


In [28]:
#UNIQUE

import numpy as np

var = np.array([1,2,3,4,5,2,7,2,5,9])

x = np.unique(var)

print(x)

[1 2 3 4 5 7 9]


In [29]:
var1 = np.array([1,2,3,4,5,2,7,2,5,9])

x = np.unique(var1,return_index=True)

print(x)

(array([1, 2, 3, 4, 5, 7, 9]), array([0, 1, 2, 3, 4, 6, 9], dtype=int64))


In [30]:
var1 = np.array([1,2,3,4,5,2,7,2,5,9])

x = np.unique(var1,return_index=True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 7, 9]), array([0, 1, 2, 3, 4, 6, 9], dtype=int64), array([1, 3, 1, 1, 2, 1, 1], dtype=int64))


In [31]:
#RESIZE

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))

print(y)


[[1 2 3]
 [4 5 6]]


In [33]:
#RESIZE

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
#FLATTEN

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.flatten)

[[1 2]
 [3 4]
 [5 6]]

<built-in method flatten of numpy.ndarray object at 0x000002A1F19B4F90>


In [35]:
#FLATTEN

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.flatten(order="F"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [36]:
#FLATTEN

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.flatten(order="c"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [37]:
#RAVEL

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.ravel(order="F"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [38]:
#RAVEL

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.ravel)

[[1 2]
 [3 4]
 [5 6]]

<built-in method ravel of numpy.ndarray object at 0x000002A1F1269890>


In [39]:
#RAVEL

var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)
print()

print(y.ravel(order="k"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]
