In [2]:
#creation of an array

import numpy as np

a = np.array([1,2,3,4,5])
print(a)

print(type(a))  #checking type whether it is list or an array


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#creation of an array  using list

import numpy as np

x = [1,2,3,4,5]

y = np.array(x)
print(y)

print(type(x))   # x is a list

print(type(y))   #y is an array

[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
#creation of an array using user input
import numpy as np

n = int(input("Enter the number of elements: "))
a = zeros(n, dtype=int)

for i in range(n):
    x = int(input("Enter element: "))
    a[i] = x

    print(a)

NameError: name 'zeros' is not defined

In [5]:
from numpy import *
n  = int(input("Enter the number of elements: "))
a = zeros(n, dtype=int)

u = len(a)
i = 0
j = 0
while i < u :
    x = int(input("Enter element: "))
    a[i] = x
    i+=1

    print(type(a))

In [2]:
#creation of one-dimensional array

import numpy as np

a = np.array([1,2,3,4,5])
print(a)

print(type(a))

print(a.ndim)  #checking the dimension of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [3]:
#creation of two-dimensional array

ar2 = np.array([[1,2,3,4]])
print(ar2)
print(ar2.ndim)

ar3 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar3)
print(ar3.ndim)



[[1 2 3 4]]
2
[[1 2 3 4]
 [1 2 3 4]]
2


In [4]:
#creation of three-dimensional array

ar2 = np.array([[[1,2,3,4]]])
print(ar2)
print(ar2.ndim)

ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]]]
3
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [5]:
#creation of multi dimensional array (let suppose array of 10 dimension)

arn = np.array([1,2,3,4,5],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [2]:
#creation of an array using user's input


l = []

for i in range(1,5):
    int_l = input("enter :")
    l.append(int_l)

print(np.array(l))


In [7]:
#creation of zero array
import numpy as np

ar_zero = np.zeros(4) #here 4 means array will be created with 4 elements
ar_zero1 = np.zeros((3,4)) #here 3 indicates that the array will be 3-dimensional and 4 indicates that the number of elements will be 4

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#creation of ones array

import numpy as np

ar_ones = np.ones(4) #here 4 means array will be created with 4 elements and each element would be 1
print(ar_ones)

print()

ar_ones1 = np.ones((3,4)) #here 3 means that the array will be of 3-dimensional and the number of elements would be 4
print(ar_ones1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#creation of empty array

import numpy as np

ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


In [14]:
#creation of an array with specified range
ar_rn = np.arange(10)
print(ar_rn)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
#creation of an array with daigonal
ar_dia = np.eye(3)  # np.eye() function creates an identity matrix 
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#to be continued 
ar_dia = np.eye(3,5)         ## np.eye() function creates an identity matrix 
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [22]:
# linespace in numpy
ar_lin  = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
#to be continued 
ar_lin  = np.linspace(1,48,num=10)
print(ar_lin)

[ 1.          6.22222222 11.44444444 16.66666667 21.88888889 27.11111111
 32.33333333 37.55555556 42.77777778 48.        ]
