In [1]:
#creating random numpy array with Rand() function
# rand(): this function is used to generate a random value between o to 1
import numpy as np

var = np.random.rand(4)

print(var)

[0.15330225 0.08612799 0.810479   0.30790706]


In [2]:
#to be continued
var1 = np.random.rand(2,5)

print(var1)

[[0.30341805 0.08901575 0.58167544 0.16612762 0.05664077]
 [0.18479007 0.90031292 0.36410889 0.06829219 0.41764175]]


In [3]:
#creating random numpy array with randn() function
# randn(): this function is used to generate a random value close to zero this may return positive or negative numbers as well
import numpy as np

var2 = np.random.randn(5)
print(var2)

[ 1.58520008 -0.16673476 -0.27811689  2.0670627   0.50094898]


In [4]:
#to be continued
var2 = np.random.randn(2,5)

print(var2)

[[-0.25195424 -0.63608626  0.19850304  0.36114031  0.04103937]
 [ 1.12075104 -0.68405914  1.44320475  1.30712936 -0.28181399]]


In [6]:
#creating random numpy array with ranf() function
# randn(): this function is used to generate a random value between o to 1 but 0 is included but 1 is excluded means array will be [0.0,1.0)
import numpy as np

var3 = np.random.ranf(4)

print(var3)



[0.8460343  0.36757278 0.85832571 0.95892361]


In [9]:
#to be continued
import numpy as np

var2 = np.random.ranf((2, 5))

print(var2)


[[0.35430422 0.26657539 0.36211042 0.33249712 0.19115903]
 [0.26804286 0.30535547 0.86860283 0.58909557 0.58261854]]


In [10]:
#creating random numpy array with randint() function
#randint(): this function is used to generate a random value in a given range 

import numpy as np

var4 = np.random.randint(5,20,5)

print(var4)

[15 19  8 11 15]


In [11]:
#to be continued
import numpy as np

var4 = np.random.randint(10,50,10)

print(var4)

[11 12 15 37 34 16 32 25 33 19]
