In [1]:
#shape

import numpy as np

var = np.array([[1,2],[2,1]])

print(var)
print()
print(var.shape)


[[1 2]
 [2 1]]

(2, 2)


In [2]:
#shape

import numpy as np

var = np.array([[1,2,3,5],[2,1,7,8]])

print(var)
print()
print(var.shape)


[[1 2 3 5]
 [2 1 7 8]]

(2, 4)


In [6]:
#converting 1-dimensional array into multi-dimensional array

import numpy as np

var = np.array([1,2,3,4,5],ndmin=5)

print(var)
print("Dimension :", var.ndim)

[[[[[1 2 3 4 5]]]]]
Dimension : 5


In [12]:
#reshape

import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)
print("Dimension :", var.ndim)
print()

x = var.reshape(3,2) #this reshape function will convert the above 1-dimensional array int 3*2 matrix

print(x)
print("Dimension :", x.ndim)

[1 2 3 4 5 6]
Dimension : 1

[[1 2]
 [3 4]
 [5 6]]
Dimension : 2


In [14]:
var3 = np.array([1,2,3,4,5,6,1,2,3])
print(var3)
print("Dimension :", var3.ndim)

print()

x1 = var3.reshape(3,3)

print(x1)

print("Dimension :", x1.ndim)

[1 2 3 4 5 6 1 2 3]
Dimension : 1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
Dimension : 2


In [15]:
#conversion of one dimension array to 3-dimensional array
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x1)

print("Dimension :", x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension : 3


In [17]:
#converison of 3-dimensional array into 1-dimensional array
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x1)

print("Dimension :", x1.ndim)

print()

one = x1.reshape(-1)
print(one)
print(one.ndim)
print("Dimension :", one.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension : 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
Dimension : 1
